[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pdf-parse"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 